In [2]:
# Goals
# 1-Import dataset
# 2-Train a classifier
# 3-Predict label for new flower
# 4-Visualize the tree

In [3]:
from sklearn.datasets import load_iris

iris = load_iris()

print(iris.feature_names)  # metadata: names of the features
print(iris.target_names)  # metadata: names of the different types of flowers

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [4]:
# print iris.data  # features and examples themselves
print (iris.data[0])  # first flower
print (iris.target[0])  # contains the labels

[ 5.1  3.5  1.4  0.2]
0


In [5]:
for i in range(len(iris.target)):
    print( "Example %d: label %s, features %s" % (i, iris.target[i], iris.data[i]))

Example 0: label 0, features [ 5.1  3.5  1.4  0.2]
Example 1: label 0, features [ 4.9  3.   1.4  0.2]
Example 2: label 0, features [ 4.7  3.2  1.3  0.2]
Example 3: label 0, features [ 4.6  3.1  1.5  0.2]
Example 4: label 0, features [ 5.   3.6  1.4  0.2]
Example 5: label 0, features [ 5.4  3.9  1.7  0.4]
Example 6: label 0, features [ 4.6  3.4  1.4  0.3]
Example 7: label 0, features [ 5.   3.4  1.5  0.2]
Example 8: label 0, features [ 4.4  2.9  1.4  0.2]
Example 9: label 0, features [ 4.9  3.1  1.5  0.1]
Example 10: label 0, features [ 5.4  3.7  1.5  0.2]
Example 11: label 0, features [ 4.8  3.4  1.6  0.2]
Example 12: label 0, features [ 4.8  3.   1.4  0.1]
Example 13: label 0, features [ 4.3  3.   1.1  0.1]
Example 14: label 0, features [ 5.8  4.   1.2  0.2]
Example 15: label 0, features [ 5.7  4.4  1.5  0.4]
Example 16: label 0, features [ 5.4  3.9  1.3  0.4]
Example 17: label 0, features [ 5.1  3.5  1.4  0.3]
Example 18: label 0, features [ 5.7  3.8  1.7  0.3]
Example 19: label 0, f

In [6]:
import numpy as np
from sklearn import tree

# here, we remove the first example of each flower
# found at indices: 0, 50, 100
test_idx = [0, 50, 100]

In [7]:
# create 2 new sets of variables, for training and testing
# training data
# remove the entires from the data and target variables
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

In [8]:
# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

In [9]:
# create new classifier
clf = tree.DecisionTreeClassifier()
# train on training data
clf.fit(train_data, train_target)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [10]:
# what we expect
print(test_target)

# what tree predicts
print(clf.predict(test_data))


[0 1 2]
[0 1 2]


## Decision Tree Visualization of data

In [12]:
import pydotplus
import collections

dot_data = tree.export_graphviz(clf,
                                feature_names=iris.feature_names,
                                class_names=iris.target_names,
                                out_file=None,
                                filled=True,
                                rounded=True)
graph = pydotplus.graph_from_dot_data(dot_data)
colors = ('turquoise', 'orange')
edges = collections.defaultdict(list)

In [13]:
for edge in graph.get_edge_list():
    edges[edge.get_source()].append(int(edge.get_destination()))
 
for edge in edges:
    edges[edge].sort()    
    for i in range(2):
        dest = graph.get_node(str(edges[edge][i]))[0]
        dest.set_fillcolor(colors[i])

In [14]:
graph.write_png('123.png')

True